AWSTemplateFormatVersion: 2010-09-09
Resources:
  myDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: mys3bucket-example.s3.amazonaws.com
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ''
        Enabled: 'true'
        DefaultRootObject: index.html
        Logging:
          IncludeCookies: 'false'
          Bucket: mys3logbucket-example.s3.amazonaws.com
          Prefix: myprefix
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: S3Origin
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: 'true'
    DependsOn:
      - MyStaticSiteBucket
      - MyLogBucket
  MyStaticSiteBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: mys3bucket-example
      WebsiteConfiguration:
        IndexDocument: index.html
  MyLogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: mys3logbucket-example
    DependsOn:
      - MyStaticSiteBucket
  MyStaticSiteBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyStaticSiteBucket
      PolicyDocument:
        Statement:
          - Sid: ReadAccess
            Action:
              - "s3:GetObject"
            Effect: "Allow"
            Resource: 'arn:aws:s3:::mys3bucket-example/*'
            Principal: "*"
          - Sid: ListWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - 'arn:aws:s3:::mys3bucket-example/*'
              - 'arn:aws:s3:::mys3bucket-example'
            Principal:
                AWS: 'arn:aws:iam::example:user/myuser'
  MyLogBucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref MyLogBucket
      PolicyDocument:
        Statement:
          - Sid: ListReadWriteDeleteAccess
            Action:
              - "s3:ListBucket"
              - "s3:GetObject"
              - "s3:PutObject"
              - "s3:DeleteObject"
            Effect: "Allow"
            Resource:
              - 'arn:aws:s3:::mys3logbucket-example/*'
              - 'arn:aws:s3:::mys3logbucket-example'
            Principal:
                AWS: 'arn:aws:iam::example:user/myuser'

